apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osca-python-app
  namespace: argocd            # ArgoCD namespace
spec:
  project: default

  source:
    repoURL: https://github.com/gad0788/argocd-app-configuration.git
    targetRevision: main       # or a tag/branch
    path: dev

  destination:
    server: https://kubernetes.default.svc
    namespace: jec-test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
