apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osca-python-app
  namespace: argocd
spec:
  project: default

  destination:
    namespace: jec-test
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/gad0788/argocd-app-configuration.git
    targetRevision: HEAD       # or a tag/branch
    path: dev
    targetRevision: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
